# Generated by Django 2.2.16 on 2022-10-24 20:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20221024_2036'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ingredientamount',
            name='ingredient amount',
        ),
        migrations.AlterField(
            model_name='ingredientamount',
            name='amount',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество ингредиентов'),
        ),
    ]
