USERS
###
GET http://127.0.0.1:8000/api/users/
Content-Type: application/json
Authorization: Token 1a4c854093c2f0bc5202f63501e02ecca1b1267f

{
  "email": "test@user14.com",
  "username": "testuser14",
  "first_name": "dadasda",
  "last_name": "dadsa",
  "password": "Zz12345678"
}
###
POST http://127.0.0.1:8000/api/auth/token/login/
Content-Type: application/json

{
  "password": "Zz123456789",
  "email": "test@user3.com"
}
###
POST http://127.0.0.1:8000/api/users/set_password/
Content-Type: application/json
Authorization: Token 1a4c854093c2f0bc5202f63501e02ecca1b1267f

{
  "new_password": "Zz123456789",
  "current_password": "Zz12345678"
}

TAGS
###
GET http://127.0.0.1:8000/api/tags/
Content-Type: application/json
Authorization: Token 1a4c854093c2f0bc5202f63501e02ecca1b1267f

Ingredients
###
GET http://127.0.0.1:8000/api/ingredients/?name=Порошок