# Generated by Django 2.2.16 on 2022-10-15 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_follow_tag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
